# tip: docker compose ignores 'version:' now; omit it.
networks:
  zta_net:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: zta_elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "${ELASTIC_PORT}:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    networks: [zta_net]

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: zta_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY="h6z2mT9JNiygeyXj4IRgNreJh0uLHyBXedJnwDZ6/Qg="
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on: [elasticsearch]
    networks: [zta_net]

  validation:
    build: ../services/validation
    container_name: zta_validation
    command: ["uvicorn","app.main:api","--host","0.0.0.0","--port","8000","--reload"]
    environment:
      DB_DSN: ${DB_DSN}
      PGOPTIONS: ${PGOPTIONS}
      DIST_THRESHOLD_KM: ${DIST_THRESHOLD_KM}
      PATH_GEOIP: /data/geolite2/GeoLite2-City.mmdb
      PATH_WIFI:  /data/wifi/wigle_sample.csv
      PATH_TLS:   /data/tls/ja3_fingerprints.csv
      PATH_DEV:   /data/device_posture/device_posture.csv
    volumes:
      - ../data:/data:ro
    ports: ["8001:8000"]
    depends_on: [elasticsearch]
    networks: [zta_net]

  trust:
    build: ../services/trust
    container_name: zta_trust
    command: ["uvicorn","app.main:api","--host","0.0.0.0","--port","8000","--reload"]
    environment:
      DB_DSN: ${DB_DSN}
      PGOPTIONS: ${PGOPTIONS}
      ALLOW_T: ${ALLOW_T}
      DENY_T:  ${DENY_T}
      SIEM_HIGH_BUMP: ${SIEM_HIGH_BUMP}
      SIEM_MED_BUMP:  ${SIEM_MED_BUMP}
      TRUST_BASE_GAIN: ${TRUST_BASE_GAIN}
      TRUST_FALLBACK_OBSERVED: ${TRUST_FALLBACK_OBSERVED}
    ports: ["8002:8000"]
    depends_on: [validation]
    networks: [zta_net]

  gateway:
    build: ../services/gateway
    container_name: zta_gateway
    command: ["uvicorn","app.main:api","--host","0.0.0.0","--port","8000","--reload"]
    environment:
      TRUST_URL: http://trust:8000
      SIEM_URL:  http://siem:8000
      DB_DSN: ${DB_DSN}
      PGOPTIONS: ${PGOPTIONS}
      TOTP_SECRET: ${TOTP_SECRET}
      # ES via headers (no creds in URL)
      ES_HOST: ${ES_HOST}
      ES_USER: ${ES_USER}
      ES_PASS: ${ES_PASS}
      ES_API_KEY: ${ES_API_KEY}
      ES_MFA_INDEX: ${ES_MFA_INDEX}
    ports: ["8003:8000"]
    depends_on:
      - trust
      - validation
    networks: [zta_net]

  siem:
    build: ../services/siem
    container_name: zta_siem
    command: ["uvicorn","app.main:api","--host","0.0.0.0","--port","8000","--reload"]
    environment:
      DB_DSN: ${DB_DSN}
      PGOPTIONS: ${PGOPTIONS}
      # ES config
      ES_HOST: ${ES_HOST}
      ES_USER: ${ES_USER}
      ES_PASS: ${ES_PASS}
      ES_API_KEY: ${ES_API_KEY}
      ES_INDEX: ${ES_INDEX}
      ES_MIRROR_INDEX: siem-alerts
      ES_SESSION_FIELD: session_id
      ES_DEFAULT_STRIDE: Tampering
      ES_DEFAULT_SEVERITY: medium
      ES_POLL_SECONDS: "20"
      ES_LOOKBACK: "2m"
      SEV_HIGH: "${SEV_HIGH}"
      SEV_MED:  "${SEV_MED}"
    ports: ["8010:8000"]
    depends_on: [gateway, validation, trust, elasticsearch]
    networks: [zta_net]

  simulator:
    build:
      context: ..
      dockerfile: scripts/simulator/Dockerfile
    container_name: zta_simulator
    working_dir: /app
    volumes:
      - ../data:/app/data:ro
    environment:
      DATA_DIR: /app/data
      CICIDS_DIR: /app/data/cicids
      WIFI_CSV: /app/data/wifi/wigle_sample.csv
      DEVICE_CSV: /app/data/device_posture/device_posture.csv
      TLS_CSV: /app/data/tls/ja3_fingerprints.csv
      VALIDATE_URL: http://validation:8000/validate
      GATEWAY_URL:  http://gateway:8000/decision
      
      SIM_MODE: ${SIM_MODE}
      SIM_SLEEP: "${SIM_SLEEP}"
      SIM_MAX_ROWS: "${SIM_MAX_ROWS}"
      SIM_MAX_PER_FILE: "${SIM_MAX_PER_FILE}"
      SIM_USE_GPS_FROM_WIFI: "${SIM_USE_GPS_FROM_WIFI}"
      
      SIM_MIN_WIFI: "${SIM_MIN_WIFI}"
      SIM_MIN_GPS:  "${SIM_MIN_GPS}"
      SIM_MIN_TLS:  "${SIM_MIN_TLS}"
      SIM_MIN_DEVICE: "${SIM_MIN_DEVICE}"
      SIM_PCT_SPOOFING: "${SIM_PCT_SPOOFING}"
      SIM_PCT_TLS_TAMPERING: "${SIM_PCT_TLS_TAMPERING}"
      SIM_PCT_DOS: "${SIM_PCT_DOS}"
      SIM_PCT_EXFIL: "${SIM_PCT_EXFIL}"
      SIM_PCT_EOP: "${SIM_PCT_EOP}"
      SIM_PCT_REPUDIATION: "${SIM_PCT_REPUDIATION}"
      SIM_INJECT_GPS_MISMATCH: "${SIM_INJECT_GPS_MISMATCH}"
      SIM_TLS_BAD_RATE: "${SIM_TLS_BAD_RATE}"
      SIM_PATCHED_TRUE_RATE: "${SIM_PATCHED_TRUE_RATE}"
      SIM_GPS_OFFSET_KM: "${SIM_GPS_OFFSET_KM}"
    depends_on: [validation, gateway]
    networks: [zta_net]