version: "3.9"

networks:
  zta_net:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: zta_elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "${ELASTIC_PORT}:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    networks:
      - zta_net

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: zta_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY="h6z2mT9JNiygeyXj4IRgNreJh0uLHyBXedJnwDZ6/Qg="
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - elasticsearch
    networks:
      - zta_net

  toxiproxy:
    image: shopify/toxiproxy:latest
    container_name: zta_toxiproxy
    ports:
      - "8474:8474" # admin API
      - "8666:8666" # example proxy port
    networks:
      - zta_net

  validation:
    build: ../services/validation
    container_name: zta_validation
    command:
      [
        "uvicorn",
        "app.main:api",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    environment:
      DB_DSN: ${DB_DSN}
      ES_URL: http://elastic:${ELASTIC_PASSWORD}@elasticsearch:9200
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8001:8000"
    depends_on:
      - elasticsearch
    networks:
      - zta_net
    develop:
      watch:
        # Sync source code into the running container
        - action: sync
          path: ../services/validation/app
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - ".venv/"
            - ".git/"
        # Rebuild the image if deps or Dockerfile change
        - action: rebuild
          path: ../services/validation/requirements.txt
        - action: rebuild
          path: ../services/validation/Dockerfile
    volumes:
      - ../data:/data:ro

  trust:
    build: ../services/trust
    container_name: zta_trust
    command:
      [
        "uvicorn",
        "app.main:api",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    environment:
      DB_DSN: ${DB_DSN}
      ES_URL: http://elastic:${ELASTIC_PASSWORD}@elasticsearch:9200
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8002:8000"
    depends_on:
      - elasticsearch
      - validation
    networks:
      - zta_net
    develop:
      watch:
        - action: sync
          path: ../services/trust/app
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - ".venv/"
            - ".git/"
        - action: rebuild
          path: ../services/trust/requirements.txt
        - action: rebuild
          path: ../services/trust/Dockerfile
    healthcheck:
      test:
        - CMD-SHELL
        - >
          python -c "import urllib.request,sys;
          sys.exit(0) if urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=2).getcode()==200
          else sys.exit(1)"
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 5

  gateway:
    build: ../services/gateway
    container_name: zta_gateway
    command:
      [
        "uvicorn",
        "app.main:api",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    environment:
      TRUST_URL: http://trust:8000
      TRUST_TIMEOUT_SECS: "10"
      DB_DSN: ${DB_DSN}
      SIEM_URL: http://siem:8000
      ES_URL: http://elastic:${ELASTIC_PASSWORD}@elasticsearch:9200
      TOTP_SECRET: JBSWY3DPEHPK3PXP # (demo, optional)
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8003:8000"
    depends_on:
      trust:
        condition: service_healthy
      siem:
        condition: service_started

    networks:
      - zta_net
    develop:
      watch:
        - action: sync
          path: ../services/gateway/app
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - ".venv/"
            - ".git/"
        - action: rebuild
          path: ../services/gateway/requirements.txt
        - action: rebuild
          path: ../services/gateway/Dockerfile

  siem:
    build: ../services/siem
    container_name: zta_siem
    command:
      [
        "uvicorn",
        "app.main:api",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    environment:
      DB_DSN: ${DB_DSN}
      TRUST_URL: http://trust:8000
      SIEM_URL: http://siem:8000
      # --- Elasticsearch poller config ---
      ES_URL: http://elastic:${ELASTIC_PASSWORD}@elasticsearch:9200
      ES_INDEX: logs-*,filebeat-*,thesis-* # comma-separated index patterns
      ES_KQL: message:"auth_failure" # simple query string
      ES_SESSION_FIELD: user.id # fallbacks to user.name, then "sess-unknown"
      ES_DEFAULT_STRIDE: Tampering # Spoofing|Tampering|Repudiation|InformationDisclosure|DoS|EoP
      ES_DEFAULT_SEVERITY: medium # low|medium|high
      ES_POLL_SECONDS: "20" # how often to poll
      ES_LOOKBACK: "2m"
      ES_MIRROR_INDEX: "siem-alerts"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8010:8000"
    depends_on:
      - validation
      - trust
    networks:
      - zta_net
    develop:
      watch:
        - action: sync
          path: ../services/siem/app
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - ".venv/"
            - ".git/"
        - action: rebuild
          path: ../services/siem/requirements.txt
        - action: rebuild
          path: ../services/siem/Dockerfile

  simulator:
    build:
      context: ..                       # repo root
      dockerfile: scripts/simulator/Dockerfile
    container_name: zta_simulator
    working_dir: /app
    volumes:
      - ../data:/app/data:ro            # makes your local data/ visible at /app/data
    environment:
      DATA_DIR: /app/data
      CICIDS_DIR: /app/data/cicids
      WIFI_CSV: /app/data/wifi/wigle_sample.csv
      DEVICE_CSV: /app/data/device_posture/device_posture.csv
      TLS_CSV: /app/data/tls/ja3_fingerprints.csv
      VALIDATE_URL: http://validation:8000/validate
      GATEWAY_URL:  http://gateway:8000/decision
      SIM_SLEEP: "0.8"
      SIM_MAX_ROWS: "150"
    depends_on:
      - validation
      - gateway
    networks:
      - zta_net
