#!/usr/bin/env python3
"""
Round 2 of thesis corrections — fixes found during a full paragraph-by-
paragraph review after round 1 (apply_thesis_corrections.py /
apply_thesis_table_corrections.py), which was thorough on Chapter 4/5's
result numbers but missed a layer of fabricated "optimization methodology"
claims in Chapter 3.5, a fabricated experimental-infrastructure description
in Chapter 3.6 (VirtualBox, "four services"), a duplicated fake evaluation
protocol in Chapter 3.8, and a few smaller inconsistencies.
"""
import docx

PATH = "/Users/knight/Apps/multi-source-ztamfa/updated/Multi- Source Context-Validation Zero Trust Framework - CORRECTED.docx"

d = docx.Document(PATH)
paras = d.paragraphs


def set_para_text(idx, new_text):
    p = paras[idx]
    if not p.runs:
        p.add_run(new_text)
        return
    p.runs[0].text = new_text
    for r in p.runs[1:]:
        r.text = ""


# ---------------------------------------------------------------------------
# Fabricated experimental infrastructure (VirtualBox, "four services")
# ---------------------------------------------------------------------------
set_para_text(292,
    "In a live deployment, endpoints would contain lightweight agents "
    "capturing raw telemetry signals. For this controlled evaluation, "
    "endpoints are simulated by a Python-based session simulator that draws "
    "real attack traffic from CIC-IDS2018 and RBA, and real signal pools "
    "from WiGLE, GeoLite2, and custom device-posture/TLS-fingerprint CSVs, "
    "rather than emulating physical or virtual endpoint hardware. Each "
    "simulated session carries: an IP address (with geolocation resolved "
    "through GeoLite2), a Wi-Fi BSSID (sourced from WiGLE, weighted toward "
    "a home-network cluster for genuine traffic and toward a foreign "
    "access point for injected Spoofing scenarios), device posture "
    "attributes (patch status, EDR status, drawn from a curated device "
    "pool), a TLS/JA3 fingerprint, and GPS coordinates. The simulator "
    "submits each session to every framework under evaluation in parallel "
    "and records every framework's decision, latency, and risk score "
    "alongside the ground-truth label."
)

set_para_text(445,
    "The architecture was deployed entirely as containerised microservices "
    "via Docker Compose — no virtual-machine endpoint emulation is used. "
    "The simulator (described in Section 3.6.1) generates each session's "
    "contextual signals directly from real data sources rather than from "
    "emulated client machines. Docker Compose deploys thirteen services: "
    "the Validation Service, Trust Engine, Authentication Gateway, SIEM "
    "Pipeline (with an Elasticsearch/Kibana backend), a Metrics service, an "
    "Indexer, the proposed framework's Ablation configuration, three "
    "baseline re-implementations (Ahmadi 2025, Phani Kumar Kanuri 2025, "
    "and Jimmy 2025 — the last kept running but excluded from quantitative "
    "comparison per Section 3.4.1), and the session simulator itself."
)

set_para_text(706,
    "Simulation vs live deployment: Endpoint telemetry was generated by a "
    "session simulator drawing from real public datasets (CIC-IDS2018, "
    "RBA, WiGLE, GeoLite2) and curated device/TLS pools, rather than "
    "captured from real physical devices in a live deployment. Real-world "
    "signal noise, device diversity, and network heterogeneity may "
    "produce different quality-score distributions than reported here."
)

# ---------------------------------------------------------------------------
# Duplicate fabricated evaluation protocol (Section 3.8)
# ---------------------------------------------------------------------------
set_para_text(588,
    "The proposed framework is evaluated against the ablation configuration "
    "and both re-implemented baselines under identical experimental "
    "conditions: the same live session stream, submitted to every "
    "configuration in parallel so that all decisions for a given session "
    "are computed from the identical underlying signals."
)

set_para_text(590,
    "The evaluation protocol is a single large-sample live evaluation "
    "rather than a repeated-trial cross-validation design: n = 2,054 "
    "sessions per configuration, drawn from CIC-IDS2018 with STRIDE-"
    "category attack injection and RBA-sourced ground truth for the "
    "Spoofing category (Section 3.7). TPR, FPR, precision, and F1 are "
    "computed directly from this sample. Statistical significance between "
    "configurations is assessed with McNemar's test on paired, matched "
    "sessions (Section 4.5) rather than a t-test, since every configuration "
    "scores the identical session set and the outcome of interest — "
    "correct or incorrect classification — is paired binary data, not a "
    "continuous measurement. An earlier draft of this section described a "
    "60/20/20 train/validation/test split with 3-fold cross-validation and "
    "10 repeated runs; that protocol was not actually implemented, and this "
    "section instead accurately describes the single-pass evaluation that "
    "was."
)

set_para_text(591,
    "Direct quantitative comparison against the baseline papers' own "
    "published figures is not meaningful, since neither paper releases its "
    "evaluation dataset or methodology for independent verification (see "
    "Chapter 4 Limitations). Ahmadi (2025) and Phani Kumar Kanuri (2025) "
    "were therefore re-implemented faithfully from their published "
    "equations and evaluated on the same real, disclosed dataset under "
    "identical conditions as the proposed framework, which is what enables "
    "the controlled comparison in Chapter 4. Jimmy (2025) publishes no "
    "risk-scoring formula and is excluded from this quantitative "
    "comparison entirely (Section 3.4.1)."
)

# ---------------------------------------------------------------------------
# Static vs dynamic weight contradiction (Rbase formula description)
# ---------------------------------------------------------------------------
set_para_text(346,
    "Wi ∈ [0,1] is the dynamically computed weight of signal i for this "
    "session (not a fixed constant — see Section 3.5.5 \"Signal Weights\" "
    "and the pseudocode in Section 3.2.4), renormalised so that ΣWi = 1 "
    "across the signals present in the session."
)

# ---------------------------------------------------------------------------
# Broken cross-reference field
# ---------------------------------------------------------------------------
set_para_text(312,
    "Figure 3.2 illustrates the workflow of the context-signal validation "
    "process, and it consists of four core stages:"
)

# ---------------------------------------------------------------------------
# Baseline-count wording ("three" vs "two" quantitative baselines)
# ---------------------------------------------------------------------------
set_para_text(466,
    "Three published frameworks are discussed in this section. Ahmadi "
    "(2025) and Phani Kumar Kanuri (2025) publish reproducible risk-"
    "scoring equations and were re-implemented faithfully and evaluated "
    "quantitatively against the proposed framework under identical "
    "experimental conditions (Chapter 4). Jimmy (2025) is also "
    "re-implemented as a running service, since its paper describes "
    "contextual factors in enough detail to approximate an equation, but "
    "is excluded from the quantitative comparison because that "
    "approximation cannot be verified against a published formula — it "
    "would not be a faithful reproduction the way the other two are."
)

set_para_text(759,
    "Empirical: the head-to-head evaluation against two published "
    "baselines with reproducible risk-scoring equations, plus an ablation "
    "configuration, on the same dataset under identical experimental "
    "conditions, provides the first controlled comparison of these "
    "approaches, establishing concrete performance benchmarks for future "
    "work in context-aware ZTA authentication."
)

d.save(PATH)
print("Round 2 structural/wording fixes saved.")
