#!/usr/bin/env python3
"""
Round 5 — content-based reapplication of Round 2 + Round 3 fixes (lost when the
document reverted to a post-Round-1 state, apparently via an external
open/autosave in Word) plus the Section 3.5.3 Es/Cs correction (Round 4,
redone here with the real 100km threshold instead of the placeholder 1000km).

Unlike Rounds 1-4, this script locates every target paragraph by searching for a
distinctive, stable substring at run time rather than a hardcoded paragraph
index — paragraph indices in this document have already proven unstable across
saves (confirmed: identical content shifted position between two reads in the
same session with no edits in between, consistent with an external editor
reflowing/resaving the file). Searching by content is immune to that.
"""
import docx

PATH = "/Users/knight/Apps/multi-source-ztamfa/updated/Multi- Source Context-Validation Zero Trust Framework - CORRECTED.docx"

d = docx.Document(PATH)
paras = d.paragraphs


def find(marker, nth=0):
    hits = [i for i, p in enumerate(paras) if marker in p.text]
    if not hits:
        raise SystemExit(f"MISSING MARKER (already fixed or moved?): {marker!r}")
    return hits[nth]


def set_text(idx, new_text):
    p = paras[idx]
    if not p.runs:
        p.add_run(new_text)
        return
    p.runs[0].text = new_text
    for r in p.runs[1:]:
        r.text = ""


fixed = []


def fix(marker, new_text, nth=0):
    idx = find(marker, nth)
    set_text(idx, new_text)
    fixed.append((idx, marker))


# ---------------------------------------------------------------------------
# VirtualBox / fabricated experimental infrastructure (5 occurrences)
# ---------------------------------------------------------------------------
fix("endpoints are simulated using VirtualBox clients",
    "In a live deployment, endpoints would contain lightweight agents "
    "capturing raw telemetry signals. For this controlled evaluation, "
    "endpoints are simulated by a Python-based session simulator that draws "
    "real attack traffic from CIC-IDS2018 and RBA, and real signal pools "
    "from WiGLE, GeoLite2, and custom device-posture/TLS-fingerprint CSVs, "
    "rather than emulating physical or virtual endpoint hardware. Each "
    "simulated session carries: an IP address (with geolocation resolved "
    "through GeoLite2), a Wi-Fi BSSID (sourced from WiGLE, weighted toward "
    "a home-network cluster for genuine traffic and toward a foreign "
    "access point for injected Spoofing scenarios), device posture "
    "attributes (patch status, EDR status, drawn from a curated device "
    "pool), a TLS/JA3 fingerprint, and GPS coordinates. The simulator "
    "submits each session to every framework under evaluation in parallel "
    "and records every framework's decision, latency, and risk score "
    "alongside the ground-truth label."
)

fix("Containerization (Docker) and virtualization (VirtualBox) ensure",
    "Experiments were conducted on an Apple MacBook Pro (13-inch, Intel "
    "Core i5, 2GHz quad-core, 16GB RAM, 512GB SSD, MacOS Sonoma) connected "
    "through 500 Mbps fibre broadband. Docker Compose containerisation "
    "ensures the setup is reproducible on Linux or Windows systems with "
    "equivalent specifications; no VM-based endpoint emulation is used. "
    "Storage: 512GB SSD"
)

fix("The architecture was deployed using VirtualBox for endpoint emulation",
    "The architecture was deployed entirely as containerised microservices "
    "via Docker Compose — no virtual-machine endpoint emulation is used. "
    "The simulator (described in Section 3.6.1) generates each session's "
    "contextual signals directly from real data sources rather than from "
    "emulated client machines. Docker Compose deploys thirteen services: "
    "the Validation Service, Trust Engine, Authentication Gateway, SIEM "
    "Pipeline (with an Elasticsearch/Kibana backend), a Metrics service, an "
    "Indexer, the proposed framework's Ablation configuration, three "
    "baseline re-implementations (Ahmadi 2025, Phani Kumar Kanuri 2025, "
    "and Jimmy 2025 — the last kept running but excluded from quantitative "
    "comparison per Section 3.4.1), and the session simulator itself."
)

fix("Custom Endpoint Logs: Generated from the VirtualBox clients",
    "Custom Endpoint Logs: Generated from the curated device-posture and "
    "TLS/JA3-fingerprint CSVs described in Section 3.6.1, not from "
    "emulated client machines."
)

fix("Endpoint telemetry was generated by VirtualBox clients",
    "Simulation vs live deployment: Endpoint telemetry was generated by a "
    "session simulator drawing from real public datasets (CIC-IDS2018, "
    "RBA, WiGLE, GeoLite2) and curated device/TLS pools, rather than "
    "captured from real physical devices in a live deployment. Real-world "
    "signal noise, device diversity, and network heterogeneity may "
    "produce different quality-score distributions than reported here."
)

# ---------------------------------------------------------------------------
# Duplicate fabricated evaluation protocol
# ---------------------------------------------------------------------------
fix("the same train/validation/test split (60/20/20), and the same evaluation protocol",
    "The proposed framework is evaluated against the ablation configuration "
    "and both re-implemented baselines under identical experimental "
    "conditions: the same live session stream, submitted to every "
    "configuration in parallel so that all decisions for a given session "
    "are computed from the identical underlying signals."
)

fix("The evaluation protocol follows four steps: (1) dataset partitioned 60/20/20",
    "The evaluation protocol is a single large-sample live evaluation "
    "rather than a repeated-trial cross-validation design: n = 2,054 "
    "sessions per configuration, drawn from CIC-IDS2018 with STRIDE-"
    "category attack injection and RBA-sourced ground truth for the "
    "Spoofing category (Section 3.7). TPR, FPR, precision, and F1 are "
    "computed directly from this sample. Statistical significance between "
    "configurations is assessed with McNemar's test on paired, matched "
    "sessions (Section 4.5) rather than a t-test, since every configuration "
    "scores the identical session set and the outcome of interest — "
    "correct or incorrect classification — is paired binary data, not a "
    "continuous measurement. An earlier draft of this section described a "
    "60/20/20 train/validation/test split with 3-fold cross-validation and "
    "10 repeated runs; that protocol was not actually implemented, and this "
    "section instead accurately describes the single-pass evaluation that "
    "was."
)

fix("Direct quantitative comparison across studies is constrained by differences",
    "Direct quantitative comparison against the baseline papers' own "
    "published figures is not meaningful, since neither paper releases its "
    "evaluation dataset or methodology for independent verification (see "
    "Chapter 4 Limitations). Ahmadi (2025) and Phani Kumar Kanuri (2025) "
    "were therefore re-implemented faithfully from their published "
    "equations and evaluated on the same real, disclosed dataset under "
    "identical conditions as the proposed framework, which is what enables "
    "the controlled comparison in Chapter 4. Jimmy (2025) publishes no "
    "risk-scoring formula and is excluded from this quantitative "
    "comparison entirely (Section 3.4.1)."
)

# ---------------------------------------------------------------------------
# Static vs dynamic weight contradiction
# ---------------------------------------------------------------------------
fix("Wi ∈ [0,1] is the static base weight of signal i, where = 1",
    "Wi ∈ [0,1] is the dynamically computed weight of signal i for this "
    "session (not a fixed constant — see Section 3.5.5 \"Signal Weights\" "
    "and the pseudocode in Section 3.2.4), renormalised so that ΣWi = 1 "
    "across the signals present in the session."
)

# ---------------------------------------------------------------------------
# Broken cross-reference field
# ---------------------------------------------------------------------------
fix("Error! Reference source not found. illustrates the workflow",
    "Figure 3.2 illustrates the workflow of the context-signal validation "
    "process, and it consists of four core stages:"
)

# ---------------------------------------------------------------------------
# Baseline-count wording (3 baselines discussed, 2 quantitatively compared)
# ---------------------------------------------------------------------------
fix("the head-to-head evaluation against three published baselines",
    "Empirical: the head-to-head evaluation against two published "
    "baselines with reproducible risk-scoring equations, plus an ablation "
    "configuration, on the same dataset under identical experimental "
    "conditions, provides the first controlled comparison of these "
    "approaches, establishing concrete performance benchmarks for future "
    "work in context-aware ZTA authentication."
)

# ---------------------------------------------------------------------------
# Fabricated "empirically optimised... 3-fold cross-validation" overview claim
# ---------------------------------------------------------------------------
fix("The framework’s parameters were empirically optimised using synthetic datasets",
    "Parameter values described in this section fall into two groups. "
    "Decision thresholds and SIEM severity weights (Section 3.5.6) were "
    "determined empirically from a real ROC sweep against live risk-score "
    "data (Figures 3.16-3.17) — see that subsection for the methodology. "
    "The freshness time constants, threat-intelligence penalty weights, "
    "and geographic consistency threshold below were set heuristically, "
    "based on domain reasoning about each signal's expected volatility and "
    "risk profile, rather than through a formal grid-search or "
    "sensitivity-analysis procedure. This is disclosed explicitly in each "
    "subsection rather than described as a formal optimisation that did "
    "not take place."
)

fix("Optimised through grid search across logarithmic time ranges",
    "These values were set heuristically based on how quickly each signal "
    "type is expected to become unreliable in practice — GPS and IP can "
    "change within minutes of travel or a network switch, while device "
    "posture changes far more slowly, over hours — rather than through a "
    "formal grid-search procedure. No such search was run, and specific "
    "per-parameter F1 scores are not reported here, since none were "
    "actually measured. Figures 3.4-3.8 illustrate the freshness decay "
    "curve implemented for each signal type."
)

# ---------------------------------------------------------------------------
# Geographic threshold: real value is 100km (compose/.env DIST_THRESHOLD_KM,
# verified against the live validation container), not the placeholder
# 1000km carried by earlier drafts.
# ---------------------------------------------------------------------------
fix("A value of 1000km maximises F1 (0.94) while maintaining FPR",
    "This value (100km) was set heuristically as a coarse threshold "
    "distinguishing plausible geolocation variance (e.g., IP geolocation "
    "resolving to a different city or region within the same country) "
    "from clear cross-border spoofing, rather than through a formal "
    "optimisation sweep. No such sweep was run this cycle, and the "
    "specific F1/FPR figures previously stated here were not measured — "
    "see Chapter 5 Future Work for a proposed empirical calibration of "
    "this threshold alongside the other heuristically-set parameters in "
    "this section."
)

# ---------------------------------------------------------------------------
# Section 3.5.3 Consistency Score / Enrichment Trust Score — the fictional
# VPN/Tor/malicious-IP/unknown-IP indicator scheme does not correspond to any
# implemented code. Real Cs = geographic-only (GPS vs WiFi/IP haversine, 100km
# threshold). Real Es = single TLS/JA3 critical-tag lookup, one 0.2x discount.
# ---------------------------------------------------------------------------
fix("Where d is the distance between signal locations and d0 is a sensitivity or threshold parameter (e.g.,1000km)",
    "Where d is the distance between the GPS-reported location and the "
    "location implied by the Wi-Fi access point (preferred) or IP "
    "geolocation (fallback, used only when no Wi-Fi signal is present), "
    "and d0 is the threshold parameter — 100km in the deployed "
    "configuration (DIST_THRESHOLD_KM)."
)

fix("Device-TLS Consistency: A binary score (0 or 1) based on whether the declared device platform",
    "This is the only consistency check the implemented system performs. "
    "An earlier draft of this section also described a binary Device-TLS "
    "Consistency check (declared device platform vs. TLS fingerprint); no "
    "such check exists anywhere in the codebase, and the claim is removed "
    "rather than retained as an unimplemented aspiration."
)

fix("Enrichment Trust Score (Es): This score is derived from threat intelligence lookups",
    "Enrichment Trust Score (Es): In the implemented system this reflects "
    "a single lookup, not a multi-indicator threat-intelligence model: "
    "whether the session's TLS/JA3 fingerprint matches a curated table of "
    "known fingerprints tagged tor_suspect, malware_family_x, "
    "scanner_tool, cloud_proxy, old_openssl, insecure_client, or "
    "honeypot_fingerprint (data/tls/ja3_fingerprints.csv). \"Tor\" "
    "detection here is via TLS client fingerprinting (Tor Browser has a "
    "distinctive JA3 signature), not an IP exit-node list — there is no "
    "IP-reputation-based VPN, Tor, malicious-IP, or unknown-IP check "
    "anywhere in the codebase."
)

fix("Es = 1 - ",
    "Es = 0.2 if the fingerprint matches a critical tag, else Es = 1.0 "
    "(the corresponding TLS signal's weight is discounted by this factor "
    "in the dynamic weighting step, not zeroed out entirely)."
)

fix("Where Ii are indicator variables and penalty are their respective weights", "")
fix("Ivpn =1, penalty = 0.7", "")
fix("Itor =1, penalty = 0.9", "")
fix("Imalicious =1, penalty = 0.1", "")
fix("Iunknown =1, penalty = 0.2", "")

fix("TOR exit nodes (0.9) carry near-maximum penalty due to strong association",
    "This single penalty value (0.2x) was set heuristically rather than "
    "through formal optimisation — a moderate rather than total discount, "
    "reflecting that a critical TLS tag is suspicious but not, on its own, "
    "conclusive proof of compromise. An earlier draft of this section "
    "described four separate indicator-weighted penalties (Tor 0.9, VPN "
    "0.7, malicious-IP 0.1, unknown-IP 0.2); that description did not "
    "correspond to any implemented code and has been replaced with the "
    "description above. Section 3.5.2 reports a real sensitivity analysis "
    "run against the penalty constants that do exist in the "
    "implementation (missing-signal 0.3x, geographic-mismatch 0.5x, "
    "critical-TLS-tag 0.2x)."
)

d.save(PATH)
print(f"Round 5: {len(fixed)} paragraphs fixed by content match.")
for idx, marker in fixed:
    print(f"  [{idx}] {marker[:70]}")
